name: Update Vehicle Miles
on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:        # Allows manual triggering
  push:
    branches:
      - main              # Also runs on pushes to main branch for testing

jobs:
  run-miles-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run miles update script
        env:
          GEOTAB_DATABASE: ${{ secrets.GEOTAB_DATABASE }}
          GEOTAB_USERNAME: ${{ secrets.GEOTAB_USERNAME }}
          GEOTAB_PASSWORD: ${{ secrets.GEOTAB_PASSWORD }}
          GEOTAB_PATH: ${{ secrets.GEOTAB_PATH }}
          MONDAY_ACCESS_TOKEN: ${{ secrets.MONDAY_ACCESS_TOKEN }}
        run: node miles.js

      - name: Log completion
        if: success()
        run: echo "Successfully updated vehicle miles"

      - name: Log failure
        if: failure()
        run: echo "Failed to update vehicle miles"
